[package]
name = "niner-marketplace"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
js = "0.5.7"
serde = "1.0.213"
sqlx = "0.8.2"
tokio = { version = "1.41.0", features = ["full"] }
tracing-subscriber = "0.3.18"
